### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by AcidOctane** [AcidOctane/homepage#6]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by artemsydorenko** [comment]
Peter Löwenbräu Griffin, Sr., born Justin Peter Griffin, is a man of Irish descent currently residing in Quahog, Rhode Island with his wife Lois Griffin. Peter's favorite pastime is watching TV, with his favorite shows consisting of Star Trek, Three's Company and Charles in Charge. He is also a huge KISS fan and followed them during the KISS Stock shows and even got a copy of Kiss Saves Santa for Christmas. Peter is also an ardent fan of Barry Manilow, though this is a fact he has been known to deny in public. Peter also mentioned that he enjoys the following breakfast cereals: Total, Trix, and Boo Berry.
Peter has a habit of proving his masculinity, not wanting Lois to fall for another man.
Peter seems to find it frustrating that he is "wrong" while Lois is "right" about issues all the time, and apparently takes these issues competitively, just waiting for the day she slips up. 
His favorite song is the Trashmen's "Surfin' Bird"

**Comment by artemsydorenko** [comment]
Peter Löwenbräu Griffin, Sr., born Justin Peter Griffin, is a man of Irish descent currently residing in Quahog, Rhode Island with his wife Lois Griffin. Peter's favorite pastime is watching TV, with his favorite shows consisting of Star Trek, Three's Company and Charles in Charge. He is also a huge KISS fan and followed them during the KISS Stock shows and even got a copy of Kiss Saves Santa for Christmas. Peter is also an ardent fan of Barry Manilow, though this is a fact he has been known to deny in public. Peter also mentioned that he enjoys the following breakfast cereals: Total, Trix, and Boo Berry.
Peter has a habit of proving his masculinity, not wanting Lois to fall for another man.
Peter seems to find it frustrating that he is "wrong" while Lois is "right" about issues all the time, and apparently takes these issues competitively, just waiting for the day she slips up.
His favorite song is the Trashmen's "Surfin' Bird"

**Comment by artemsydorenko** [comment]
Peter Löwenbräu Griffin, Sr., born Justin Peter Griffin, is a man of Irish descent currently residing in Quahog, Rhode Island with his wife Lois Griffin. Peter's favorite pastime is watching TV, with his favorite shows consisting of Star Trek, Three's Company and Charles in Charge. He is also a huge KISS fan and followed them during the KISS Stock shows and even got a copy of Kiss Saves Santa for Christmas. Peter is also an ardent fan of Barry Manilow, though this is a fact he has been known to deny in public. Peter also mentioned that he enjoys the following breakfast cereals: Total, Trix, and Boo Berry.
Peter has a habit of proving his masculinity, not wanting Lois to fall for another man.
Peter seems to find it frustrating that he is "wrong" while Lois is "right" about issues all the time, and apparently takes these issues competitively, just waiting for the day she slips up.
His favorite song is the Trashmen's "Surfin' Bird"

**Comment by AcidOctane** [comment]
Peter Löwenbräu Griffin, Sr., born Justin Peter Griffin, is a man of Irish descent currently residing in Quahog, Rhode Island with his wife Lois Griffin. Peter's favorite pastime is watching TV, with his favorite shows consisting of Star Trek, Three's Company and Charles in Charge. He is also a huge KISS fan and followed them during the KISS Stock shows and even got a copy of Kiss Saves Santa for Christmas. Peter is also an ardent fan of Barry Manilow, though this is a fact he has been known to deny in public. Peter also mentioned that he enjoys the following breakfast cereals: Total, Trix, and Boo Berry.
Peter has a habit of proving his masculinity, not wanting Lois to fall for another man.
Peter seems to find it frustrating that he is "wrong" while Lois is "right" about issues all the time, and apparently takes these issues competitively, just waiting for the day she slips up.
His favorite song is the Trashmen's "Surfin' Bird"

**Comment by AcidOctane** [comment]
# Resume

## **Peter Löwenbräu Griffin, Sr.**

born Justin Peter Griffin, is a man of Irish descent currently residing in **Quahog, Rhode Island** with his wife Lois Griffin. 
Peter's favorite pastime is **watching TV**, with his favorite shows consisting of **Star Trek**, **Three's Company** and **Charles in Charge**. 
He is also a huge **KISS** fan and followed them during the KISS Stock shows and even got a copy of Kiss Saves Santa for Christmas. 
Peter is also an ardent fan of **Barry Manilow**, though this is a fact he has been known to deny in public. 
Peter enjoys the following breakfast cereals: **Total**, **Trix**, and **Boo Berry**.
His favorite song is the **Trashmen's "Surfin' Bird"**.

**Comment by s1dneyoctane** [comment]
Peter Löwenbräu Griffin, Sr.

Born Justin Peter Griffin, is a man of Irish descent currently residing in Quahog, Rhode Island with his wife Lois Griffin.
Steven Hemsley Gerber (actual name)
Kichwa Tembo (African name)
Gggwggwg (Hebrew name)
Neng2 Shen (Chinese name)
EXPERIENCE
25th September 2005

Shipping Department at The Pawtucket Brewery

working for a mentally handicapped man whom he can’t understand, but is more qualified than him
19th September 2001 – 31st October 2005

Fisherman at The S.S. More Powerful Than Superman, Batman, Spider-Man, and The Incredible Hulk Put Together

catch fish, ride a boat, don't wreck it (failed)
31st January 1999 – 5th September 2001

Line worker at Happy-Go-Lucky Toy Factory

check the line for dangerous toys
