### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by AcidOctane** [AcidOctane/homepage#7]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by artemsydorenko** [comment]
Instagram: https://www.instagram.com/peterpumpkineater69/

**Comment by artemsydorenko** [comment]
Phone (401) 555-1125
